# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # setup python
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_BIGQUERY_KEYFILE}}
          
      - name: Install dependencies
        run: |
          pip install dbt
          dbt deps --target prod
          
      # Add dbt seed or other commands here if needed
      - name: Run dbt models
        run: dbt run --profiles-dir . --target prod

      - name: Test dbt models
        run: dbt test --profiles-dir . --target prod
